name: "Terraform CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-ci:
    name: "Lint & Validate Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Check Formatting
        run: terraform fmt -check

      - name: Initialize Terraform
        run: terraform init -backend=false

      - name: Validate Terraform Syntax
        run: terraform validate
